language: python
dist: xenial
sudo: true

python:
- 2.7
- 3.5
- 3.6
- 3.7

env:
  global:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - PIP_USE_MIRRORS=true

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0
    - python: 2.7
      env: DJANGO=2.1

cache:
  directories:
  - $HOME/.cache/pip

install:
- pip install -q Django==$DJANGO
- python setup.py -q install

script:
- python setup.py test

after_success: coveralls

notifications:
  email:
    on_success: change
    on_failure: always
