language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO=1.9
  - DJANGO=1.10
install:
  - pip install -q Django==$DJANGO
  - python setup.py -q install
script:
  - python setup.py test
notifications:
  email: false
