language: python
dist: xenial
sudo: true

python:
- 2.7
- 3.5
- 3.6
- 3.7

env:
  global:
  - DJANGO=1.9
  - DJANGO=1.10
  - PIP_USE_MIRRORS=true

cache:
  directories:
  - $HOME/.cache/pip

install:
- pip install -q Django==$DJANGO
- python setup.py -q install

script:
- python setup.py test

notifications:
  email:
    on_success: change
    on_failure: always
